# comentario -> para executar digite make 
# Flags de compilação processador: -march=ivybridge -O3 -pipe

all: compile
	
compile:
	clear
	gcc -o 1 Coktail_sort.c -fopenmp -march=ivybridge -O3 -pipe
	clear
	@echo " "
	@echo "Compilaçao concluida"
	@echo " "

clean:
	rm -rf *.out

